import type {
  Integration,
  MarketplaceIntegration,
  APIKey,
  Webhook,
  IntegrationLog,
  IntegrationId,
  APIKeyId,
  WebhookId
} from './integrationTypes';

const now = () => new Date();

// Seed Active Integrations
export const seedIntegrations: Integration[] = [
  {
    id: 'INT-EMAIL-001' as IntegrationId,
    name: 'Gmail',
    slug: 'gmail',
    description: 'Connect your Gmail account to send and receive emails',
    category: 'email',
    provider: 'Google',
    logoUrl: '📧',
    status: 'active',
    authType: 'oauth2',
    isActive: true,
    isPremium: false,
    connectedAt: new Date('2024-03-01'),
    lastSyncedAt: new Date('2024-03-28'),
    features: ['Send emails', 'Receive emails', 'Email tracking', 'Templates'],
    supportedActions: ['send', 'receive', 'search', 'label'],
    settings: {
      syncEnabled: true,
      syncInterval: 15,
      webhooksEnabled: true,
      autoRetry: true,
      retryAttempts: 3,
    },
    metadata: {
      version: '2.0',
      documentationUrl: 'https://developers.google.com/gmail/api',
      supportEmail: 'support@google.com',
    },
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-28'),
  },
  {
    id: 'INT-CAL-001' as IntegrationId,
    name: 'Google Calendar',
    slug: 'google-calendar',
    description: 'Sync meetings and schedules with Google Calendar',
    category: 'calendar',
    provider: 'Google',
    logoUrl: '📅',
    status: 'active',
    authType: 'oauth2',
    isActive: true,
    isPremium: false,
    connectedAt: new Date('2024-03-05'),
    lastSyncedAt: new Date('2024-03-28'),
    features: ['Create events', 'Sync calendar', 'Meeting reminders', 'Availability check'],
    supportedActions: ['create_event', 'update_event', 'delete_event', 'get_availability'],
    settings: {
      syncEnabled: true,
      syncInterval: 30,
      webhooksEnabled: true,
      autoRetry: true,
      retryAttempts: 3,
    },
    metadata: {
      version: '3.0',
      documentationUrl: 'https://developers.google.com/calendar',
    },
    createdAt: new Date('2024-03-05'),
  },
  {
    id: 'INT-COMM-001' as IntegrationId,
    name: 'Slack',
    slug: 'slack',
    description: 'Get notifications and updates in Slack channels',
    category: 'communication',
    provider: 'Slack Technologies',
    logoUrl: '💬',
    status: 'active',
    authType: 'oauth2',
    isActive: true,
    isPremium: false,
    connectedAt: new Date('2024-03-10'),
    lastSyncedAt: new Date('2024-03-28'),
    features: ['Send notifications', 'Create channels', 'Post messages', 'File sharing'],
    supportedActions: ['send_message', 'create_channel', 'upload_file'],
    settings: {
      syncEnabled: false,
      syncInterval: 0,
      webhooksEnabled: true,
      autoRetry: true,
      retryAttempts: 5,
    },
    metadata: {
      version: '1.0',
      documentationUrl: 'https://api.slack.com',
      supportEmail: 'support@slack.com',
    },
    createdAt: new Date('2024-03-10'),
  },
];

// Seed Marketplace Integrations
export const seedMarketplaceIntegrations: MarketplaceIntegration[] = [
  // Email
  {
    id: 'MKT-EMAIL-001',
    name: 'Gmail',
    slug: 'gmail',
    description: 'Connect your Gmail account to send and receive emails',
    longDescription: 'Gmail integration allows you to send and receive emails directly from your CRM. Track email opens, clicks, and responses. Use templates and schedule emails.',
    category: 'email',
    provider: 'Google',
    logoUrl: '📧',
    screenshots: [],
    isPremium: false,
    isPopular: true,
    isNew: false,
    authType: 'oauth2',
    features: ['Send emails', 'Receive emails', 'Email tracking', 'Templates', 'Scheduling'],
    supportedActions: ['send', 'receive', 'search', 'label', 'archive'],
    pricing: { free: true, currency: 'USD' },
    rating: 4.8,
    reviewCount: 1250,
    installCount: 15000,
    metadata: {
      version: '2.0',
      documentationUrl: 'https://developers.google.com/gmail/api',
      supportEmail: 'support@google.com',
      website: 'https://mail.google.com',
    },
  },
  {
    id: 'MKT-EMAIL-002',
    name: 'Outlook',
    slug: 'outlook',
    description: 'Microsoft Outlook email integration',
    longDescription: 'Connect your Microsoft Outlook account for seamless email communication. Sync contacts, calendar, and emails.',
    category: 'email',
    provider: 'Microsoft',
    logoUrl: '📨',
    screenshots: [],
    isPremium: false,
    isPopular: true,
    isNew: false,
    authType: 'oauth2',
    features: ['Send emails', 'Receive emails', 'Calendar sync', 'Contact sync'],
    supportedActions: ['send', 'receive', 'search', 'calendar_sync'],
    pricing: { free: true, currency: 'USD' },
    rating: 4.6,
    reviewCount: 890,
    installCount: 12000,
    metadata: {
      version: '1.5',
      documentationUrl: 'https://docs.microsoft.com/graph',
      supportEmail: 'support@microsoft.com',
      website: 'https://outlook.com',
    },
  },
  // Calendar
  {
    id: 'MKT-CAL-001',
    name: 'Google Calendar',
    slug: 'google-calendar',
    description: 'Sync meetings and schedules with Google Calendar',
    longDescription: 'Google Calendar integration helps you manage meetings, check availability, and schedule appointments directly from your CRM.',
    category: 'calendar',
    provider: 'Google',
    logoUrl: '📅',
    screenshots: [],
    isPremium: false,
    isPopular: true,
    isNew: false,
    authType: 'oauth2',
    features: ['Create events', 'Sync calendar', 'Meeting reminders', 'Availability check'],
    supportedActions: ['create_event', 'update_event', 'delete_event', 'get_availability'],
    pricing: { free: true, currency: 'USD' },
    rating: 4.7,
    reviewCount: 780,
    installCount: 10000,
    metadata: {
      version: '3.0',
      documentationUrl: 'https://developers.google.com/calendar',
      supportEmail: 'support@google.com',
      website: 'https://calendar.google.com',
    },
  },
  // Communication
  {
    id: 'MKT-COMM-001',
    name: 'Slack',
    slug: 'slack',
    description: 'Get notifications and updates in Slack channels',
    longDescription: 'Slack integration sends real-time notifications about leads, deals, and activities to your team channels. Create automated workflows.',
    category: 'communication',
    provider: 'Slack Technologies',
    logoUrl: '💬',
    screenshots: [],
    isPremium: false,
    isPopular: true,
    isNew: false,
    authType: 'oauth2',
    features: ['Send notifications', 'Create channels', 'Post messages', 'File sharing', 'Slash commands'],
    supportedActions: ['send_message', 'create_channel', 'upload_file', 'invite_user'],
    pricing: { free: true, currency: 'USD' },
    rating: 4.9,
    reviewCount: 2100,
    installCount: 25000,
    metadata: {
      version: '1.0',
      documentationUrl: 'https://api.slack.com',
      supportEmail: 'support@slack.com',
      website: 'https://slack.com',
    },
  },
  {
    id: 'MKT-COMM-002',
    name: 'Microsoft Teams',
    slug: 'microsoft-teams',
    description: 'Collaborate and communicate with Microsoft Teams',
    longDescription: 'Microsoft Teams integration enables team collaboration with chat, meetings, and file sharing capabilities.',
    category: 'communication',
    provider: 'Microsoft',
    logoUrl: '👥',
    screenshots: [],
    isPremium: false,
    isPopular: true,
    isNew: false,
    authType: 'oauth2',
    features: ['Team chat', 'Video meetings', 'File sharing', 'Notifications'],
    supportedActions: ['send_message', 'create_meeting', 'share_file'],
    pricing: { free: true, currency: 'USD' },
    rating: 4.5,
    reviewCount: 650,
    installCount: 8000,
    metadata: {
      version: '2.0',
      documentationUrl: 'https://docs.microsoft.com/microsoftteams',
      supportEmail: 'support@microsoft.com',
      website: 'https://teams.microsoft.com',
    },
  },
  // Marketing
  {
    id: 'MKT-MARK-001',
    name: 'Mailchimp',
    slug: 'mailchimp',
    description: 'Email marketing automation with Mailchimp',
    longDescription: 'Sync your contacts with Mailchimp and run email marketing campaigns. Track engagement and automate workflows.',
    category: 'marketing',
    provider: 'Intuit Mailchimp',
    logoUrl: '🐒',
    screenshots: [],
    isPremium: true,
    isPopular: true,
    isNew: false,
    authType: 'oauth2',
    features: ['Contact sync', 'Campaign management', 'Analytics', 'Automation', 'A/B testing'],
    supportedActions: ['sync_contacts', 'create_campaign', 'get_analytics'],
    pricing: { free: false, startingPrice: 29, currency: 'USD' },
    rating: 4.6,
    reviewCount: 1540,
    installCount: 18000,
    metadata: {
      version: '3.0',
      documentationUrl: 'https://mailchimp.com/developer',
      supportEmail: 'support@mailchimp.com',
      website: 'https://mailchimp.com',
    },
  },
  {
    id: 'MKT-MARK-002',
    name: 'HubSpot',
    slug: 'hubspot',
    description: 'Inbound marketing and sales platform',
    longDescription: 'HubSpot integration provides powerful marketing automation, lead nurturing, and analytics capabilities.',
    category: 'marketing',
    provider: 'HubSpot',
    logoUrl: '🔶',
    screenshots: [],
    isPremium: true,
    isPopular: true,
    isNew: false,
    authType: 'oauth2',
    features: ['Marketing automation', 'Lead scoring', 'Email campaigns', 'Analytics', 'CRM sync'],
    supportedActions: ['sync_contacts', 'create_deal', 'track_activity', 'run_campaign'],
    pricing: { free: false, startingPrice: 45, currency: 'USD' },
    rating: 4.7,
    reviewCount: 980,
    installCount: 15000,
    metadata: {
      version: '2.5',
      documentationUrl: 'https://developers.hubspot.com',
      supportEmail: 'support@hubspot.com',
      website: 'https://hubspot.com',
    },
  },
  // Payment
  {
    id: 'MKT-PAY-001',
    name: 'Stripe',
    slug: 'stripe',
    description: 'Accept payments and manage subscriptions',
    longDescription: 'Stripe integration allows you to accept payments, manage subscriptions, and track revenue directly from your CRM.',
    category: 'payment',
    provider: 'Stripe',
    logoUrl: '💳',
    screenshots: [],
    isPremium: false,
    isPopular: true,
    isNew: false,
    authType: 'api_key',
    features: ['Payment processing', 'Subscription management', 'Invoicing', 'Revenue tracking'],
    supportedActions: ['create_payment', 'create_subscription', 'create_invoice', 'refund'],
    pricing: { free: true, currency: 'USD' },
    rating: 4.8,
    reviewCount: 2200,
    installCount: 22000,
    metadata: {
      version: '2024.1',
      documentationUrl: 'https://stripe.com/docs/api',
      supportEmail: 'support@stripe.com',
      website: 'https://stripe.com',
    },
  },
  {
    id: 'MKT-PAY-002',
    name: 'PayPal',
    slug: 'paypal',
    description: 'PayPal payment integration',
    longDescription: 'Accept PayPal payments and manage transactions seamlessly within your CRM workflow.',
    category: 'payment',
    provider: 'PayPal',
    logoUrl: '💰',
    screenshots: [],
    isPremium: false,
    isPopular: true,
    isNew: false,
    authType: 'oauth2',
    features: ['Payment processing', 'Transaction tracking', 'Refunds', 'Recurring payments'],
    supportedActions: ['create_payment', 'get_transaction', 'issue_refund'],
    pricing: { free: true, currency: 'USD' },
    rating: 4.4,
    reviewCount: 890,
    installCount: 12000,
    metadata: {
      version: '2.0',
      documentationUrl: 'https://developer.paypal.com',
      supportEmail: 'support@paypal.com',
      website: 'https://paypal.com',
    },
  },
  // Storage
  {
    id: 'MKT-STOR-001',
    name: 'Google Drive',
    slug: 'google-drive',
    description: 'Store and share files with Google Drive',
    longDescription: 'Google Drive integration lets you attach files from Drive to your records and automatically save documents.',
    category: 'storage',
    provider: 'Google',
    logoUrl: '📁',
    screenshots: [],
    isPremium: false,
    isPopular: true,
    isNew: false,
    authType: 'oauth2',
    features: ['File upload', 'File sharing', 'Folder sync', 'Document collaboration'],
    supportedActions: ['upload_file', 'download_file', 'share_file', 'create_folder'],
    pricing: { free: true, currency: 'USD' },
    rating: 4.7,
    reviewCount: 1100,
    installCount: 16000,
    metadata: {
      version: '3.0',
      documentationUrl: 'https://developers.google.com/drive',
      supportEmail: 'support@google.com',
      website: 'https://drive.google.com',
    },
  },
  {
    id: 'MKT-STOR-002',
    name: 'Dropbox',
    slug: 'dropbox',
    description: 'Cloud storage and file synchronization',
    longDescription: 'Dropbox integration provides secure file storage and sharing capabilities for your CRM documents.',
    category: 'storage',
    provider: 'Dropbox',
    logoUrl: '📦',
    screenshots: [],
    isPremium: false,
    isPopular: false,
    isNew: false,
    authType: 'oauth2',
    features: ['File storage', 'File sharing', 'Version control', 'Team folders'],
    supportedActions: ['upload_file', 'download_file', 'share_link'],
    pricing: { free: true, currency: 'USD' },
    rating: 4.5,
    reviewCount: 670,
    installCount: 9000,
    metadata: {
      version: '2.0',
      documentationUrl: 'https://www.dropbox.com/developers',
      supportEmail: 'support@dropbox.com',
      website: 'https://dropbox.com',
    },
  },
  // Social
  {
    id: 'MKT-SOC-001',
    name: 'LinkedIn',
    slug: 'linkedin',
    description: 'Connect with LinkedIn for lead generation',
    longDescription: 'LinkedIn integration helps you find and connect with prospects, import contacts, and track social selling activities.',
    category: 'social',
    provider: 'LinkedIn',
    logoUrl: '🔗',
    screenshots: [],
    isPremium: true,
    isPopular: true,
    isNew: false,
    authType: 'oauth2',
    features: ['Contact import', 'Lead generation', 'Social selling', 'Company insights'],
    supportedActions: ['import_contacts', 'get_profile', 'send_message'],
    pricing: { free: false, startingPrice: 19, currency: 'USD' },
    rating: 4.6,
    reviewCount: 820,
    installCount: 11000,
    metadata: {
      version: '1.0',
      documentationUrl: 'https://docs.microsoft.com/linkedin',
      supportEmail: 'support@linkedin.com',
      website: 'https://linkedin.com',
    },
  },
  // Analytics
  {
    id: 'MKT-ANA-001',
    name: 'Google Analytics',
    slug: 'google-analytics',
    description: 'Track website analytics and user behavior',
    longDescription: 'Google Analytics integration provides insights into website traffic, user behavior, and conversion tracking.',
    category: 'analytics',
    provider: 'Google',
    logoUrl: '📊',
    screenshots: [],
    isPremium: false,
    isPopular: true,
    isNew: false,
    authType: 'oauth2',
    features: ['Website tracking', 'Conversion tracking', 'User analytics', 'Custom reports'],
    supportedActions: ['track_event', 'get_report', 'create_goal'],
    pricing: { free: true, currency: 'USD' },
    rating: 4.7,
    reviewCount: 1450,
    installCount: 20000,
    metadata: {
      version: '4.0',
      documentationUrl: 'https://developers.google.com/analytics',
      supportEmail: 'support@google.com',
      website: 'https://analytics.google.com',
    },
  },
  // Telephony
  {
    id: 'MKT-TEL-001',
    name: 'Twilio',
    slug: 'twilio',
    description: 'SMS and voice communication platform',
    longDescription: 'Twilio integration enables SMS messaging, voice calls, and phone number management directly from your CRM.',
    category: 'telephony',
    provider: 'Twilio',
    logoUrl: '📞',
    screenshots: [],
    isPremium: true,
    isPopular: true,
    isNew: false,
    authType: 'api_key',
    features: ['SMS messaging', 'Voice calls', 'Call recording', 'Phone numbers'],
    supportedActions: ['send_sms', 'make_call', 'get_recording'],
    pricing: { free: false, startingPrice: 0.0075, currency: 'USD' },
    rating: 4.8,
    reviewCount: 1680,
    installCount: 14000,
    metadata: {
      version: '2024.1',
      documentationUrl: 'https://www.twilio.com/docs',
      supportEmail: 'support@twilio.com',
      website: 'https://twilio.com',
    },
  },
  {
    id: 'MKT-CUST-001',
    name: 'Zapier',
    slug: 'zapier',
    description: 'Connect to 5000+ apps with Zapier',
    longDescription: 'Zapier integration allows you to create custom workflows and connect with thousands of apps without coding.',
    category: 'custom',
    provider: 'Zapier',
    logoUrl: '⚡',
    screenshots: [],
    isPremium: true,
    isPopular: true,
    isNew: false,
    authType: 'api_key',
    features: ['Custom workflows', '5000+ app integrations', 'Automation', 'Multi-step zaps'],
    supportedActions: ['create_zap', 'trigger_zap'],
    pricing: { free: false, startingPrice: 19.99, currency: 'USD' },
    rating: 4.9,
    reviewCount: 3200,
    installCount: 35000,
    metadata: {
      version: '14.0',
      documentationUrl: 'https://zapier.com/developer',
      supportEmail: 'support@zapier.com',
      website: 'https://zapier.com',
    },
  },
];

// Seed API Keys
export const seedAPIKeys: APIKey[] = [
  {
    id: 'KEY-001' as APIKeyId,
    name: 'Production API Key',
    key: 'pk_live_51Hxxx...xxx',
    environment: 'production',
    permissions: ['read', 'write', 'delete'],
    rateLimit: 1000,
    isActive: true,
    lastUsedAt: new Date('2024-03-28'),
    createdAt: new Date('2024-01-15'),
    createdBy: 'Admin User',
  },
  {
    id: 'KEY-002' as APIKeyId,
    name: 'Sandbox API Key',
    key: 'pk_test_51Hxxx...xxx',
    environment: 'sandbox',
    permissions: ['read', 'write'],
    rateLimit: 100,
    isActive: true,
    lastUsedAt: new Date('2024-03-27'),
    createdAt: new Date('2024-01-15'),
    createdBy: 'Admin User',
  },
];

// Seed Webhooks
export const seedWebhooks: Webhook[] = [
  {
    id: 'WH-001' as WebhookId,
    name: 'Lead Created Webhook',
    url: 'https://api.example.com/webhooks/lead-created',
    events: ['lead.created', 'lead.updated'],
    isActive: true,
    secret: 'whsec_xxx',
    headers: { 'X-Custom-Header': 'value' },
    retryPolicy: {
      maxRetries: 3,
      backoffMultiplier: 2,
    },
    lastTriggeredAt: new Date('2024-03-28'),
    successCount: 1250,
    failureCount: 15,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'WH-002' as WebhookId,
    name: 'Deal Won Webhook',
    url: 'https://api.example.com/webhooks/deal-won',
    events: ['deal.won', 'deal.lost'],
    isActive: true,
    retryPolicy: {
      maxRetries: 5,
      backoffMultiplier: 1.5,
    },
    lastTriggeredAt: new Date('2024-03-27'),
    successCount: 450,
    failureCount: 8,
    createdAt: new Date('2024-02-10'),
  },
];

// Seed Integration Logs
export const seedIntegrationLogs: IntegrationLog[] = [
  {
    id: 'LOG-001',
    integrationId: 'INT-EMAIL-001' as IntegrationId,
    integrationName: 'Gmail',
    action: 'sync',
    status: 'success',
    message: 'Successfully synced 45 emails',
    details: { emailCount: 45, duration: 2500 },
    duration: 2500,
    timestamp: new Date('2024-03-28T10:30:00'),
  },
  {
    id: 'LOG-002',
    integrationId: 'INT-CAL-001' as IntegrationId,
    integrationName: 'Google Calendar',
    action: 'sync',
    status: 'success',
    message: 'Synced 12 calendar events',
    details: { eventCount: 12 },
    duration: 1200,
    timestamp: new Date('2024-03-28T10:15:00'),
  },
  {
    id: 'LOG-003',
    integrationId: 'INT-COMM-001' as IntegrationId,
    integrationName: 'Slack',
    action: 'webhook_trigger',
    status: 'success',
    message: 'Sent notification to #sales channel',
    details: { channel: '#sales', message: 'New lead created' },
    duration: 450,
    timestamp: new Date('2024-03-28T09:45:00'),
  },
  {
    id: 'LOG-004',
    integrationId: 'INT-EMAIL-001' as IntegrationId,
    integrationName: 'Gmail',
    action: 'error',
    status: 'failed',
    message: 'Rate limit exceeded',
    details: { error: 'Too many requests', retryAfter: 60 },
    timestamp: new Date('2024-03-27T16:20:00'),
  },
];
